### ISSUE TITLE
License_plate

### ISSUE THREAD

**Issue by rutujar** [i008/pyimagegurus#1]
In the folder pyimagegurus/src/license_plate_m3_64/. How to  run the program and what steps to be followed. Help needed ASAP.

**Comment by rutujar** [comment]
when i run the program
* 
python3 recognize_lp_chars.py --images ../images --char-classifier output/char.cpickle --digit-classifier output/digit.cpickle
Traceback (most recent call last):
  File "recognize_lp_chars.py", line 22, in <module>
    charModel = cPickle.loads(open(args["char_classifier"]).read())
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

*
python3 train_simple_lp_char_reco.py --fonts ../fonts --char-classifier output/char.cpickle --digit-classifier output/digit.cpickle
[INFO] describing font examples...
[INFO] fitting character model...
Traceback (most recent call last):
  File "train_simple_lp_char_reco.py", line 66, in <module>
    charModel.fit(alphabetData, alphabetLabels)
  File "/home/rutuja/.local/lib/python3.6/site-packages/sklearn/svm/classes.py", line 229, in fit
    accept_large_sparse=False)
  File "/home/rutuja/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 756, in check_X_y
    estimator=estimator)
  File "/home/rutuja/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 552, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

how to solve this error.help needed asap
